import { AssetPosition, Portfolio, MarketAlert, NewsItem, DividendEvent, EarningEvent, TickerSuggestion } from '../types';

export const DEFAULT_PORTFOLIOS: Portfolio[] = [
  { id: 'p1', name: 'Główny Portfel Wzrostowy', icon: 'Briefcase', color: '#10B981' },
  { id: 'p2', name: 'Emerytura IKE / IKZE', icon: 'ShieldCheck', color: '#3B82F6' },
  { id: 'p3', name: 'Krypto Spekulacja', icon: 'Coins', color: '#F59E0B' },
];

export const GLOBAL_TICKERS: TickerSuggestion[] = [
  { symbol: 'NVDA', name: 'NVIDIA Corporation', category: 'stocks_us', price: 128.50, currency: 'USD', change24h: 4.85 },
  { symbol: 'AAPL', name: 'Apple Inc.', category: 'stocks_us', price: 224.30, currency: 'USD', change24h: 1.12 },
  { symbol: 'TSLA', name: 'Tesla Inc.', category: 'stocks_us', price: 210.80, currency: 'USD', change24h: -2.40 },
  { symbol: 'MSFT', name: 'Microsoft Corp.', category: 'stocks_us', price: 448.90, currency: 'USD', change24h: 0.85 },
  { symbol: 'CDR.WA', name: 'CD Projekt S.A.', category: 'stocks_pl', price: 168.20, currency: 'PLN', change24h: 5.40 },
  { symbol: 'PKO.WA', name: 'PKO Bank Polski', category: 'stocks_pl', price: 58.40, currency: 'PLN', change24h: -0.60 },
  { symbol: 'DNP.WA', name: 'Dino Polska S.A.', category: 'stocks_pl', price: 412.00, currency: 'PLN', change24h: 2.10 },
  { symbol: 'SPY', name: 'SPDR S&P 500 ETF Trust', category: 'etf', price: 542.10, currency: 'USD', change24h: 0.45 },
  { symbol: 'QQQ', name: 'Invesco QQQ Trust', category: 'etf', price: 478.00, currency: 'USD', change24h: 1.25 },
  { symbol: 'BTC', name: 'Bitcoin', category: 'crypto', price: 67450.00, currency: 'USD', change24h: 3.80 },
  { symbol: 'ETH', name: 'Ethereum', category: 'crypto', price: 3480.00, currency: 'USD', change24h: 2.45 },
  { symbol: 'SOL', name: 'Solana', category: 'crypto', price: 184.20, currency: 'USD', change24h: 8.10 },
  { symbol: 'XAU', name: 'Złoto (Gold Ounce)', category: 'gold', price: 2425.50, currency: 'USD', change24h: 0.90 },
  { symbol: 'XAG', name: 'Srebro (Silver Ounce)', category: 'silver', price: 31.10, currency: 'USD', change24h: -1.20 },
  { symbol: 'USDPLN', name: 'Dolar amerykański / Polski Złoty', category: 'forex', price: 3.98, currency: 'PLN', change24h: -0.15 },
  { symbol: 'TBT', name: 'ProShares UltraShort 20+ Year Treasury', category: 'bonds', price: 34.60, currency: 'USD', change24h: -0.80 },
];

export const INITIAL_POSITIONS: AssetPosition[] = [
  {
    id: 'pos-1',
    portfolioId: 'p1',
    ticker: 'NVDA',
    name: 'NVIDIA Corporation',
    category: 'stocks_us',
    shares: 40,
    buyPrice: 92.00,
    currentPrice: 128.50,
    currency: 'USD',
    purchaseDate: '2024-03-12',
    commission: 2.50,
    notes: 'Kupione pod rozwój układów AI Blackwell.',
    history24h: [122, 124, 123.5, 125, 126.8, 128.50],
  },
  {
    id: 'pos-2',
    portfolioId: 'p1',
    ticker: 'AAPL',
    name: 'Apple Inc.',
    category: 'stocks_us',
    shares: 25,
    buyPrice: 185.00,
    currentPrice: 224.30,
    currency: 'USD',
    purchaseDate: '2024-01-15',
    commission: 1.50,
    notes: 'Stabilna dywidenda i pozycja na rynku.',
    history24h: [220, 221.5, 222, 223.1, 224.0, 224.30],
  },
  {
    id: 'pos-3',
    portfolioId: 'p1',
    ticker: 'CDR.WA',
    name: 'CD Projekt S.A.',
    category: 'stocks_pl',
    shares: 120,
    buyPrice: 112.00,
    currentPrice: 168.20,
    currency: 'PLN',
    purchaseDate: '2023-11-05',
    commission: 5.00,
    notes: 'Wiedźmin 4 w fazie pełnej produkcji.',
    history24h: [158, 160, 162, 161.5, 165, 168.20],
  },
  {
    id: 'pos-4',
    portfolioId: 'p1',
    ticker: 'SPY',
    name: 'SPDR S&P 500 ETF Trust',
    category: 'etf',
    shares: 15,
    buyPrice: 510.00,
    currentPrice: 542.10,
    currency: 'USD',
    purchaseDate: '2024-02-20',
    commission: 0.00,
    notes: 'Dywersyfikacja kapitału w USA.',
    history24h: [539, 540, 541.2, 540.8, 541.9, 542.10],
  },
  {
    id: 'pos-5',
    portfolioId: 'p2',
    ticker: 'SPY',
    name: 'SPDR S&P 500 ETF Trust',
    category: 'etf',
    shares: 30,
    buyPrice: 480.00,
    currentPrice: 542.10,
    currency: 'USD',
    purchaseDate: '2023-09-10',
    commission: 0.00,
    notes: 'Konto emerytalne zwolnione z podatku Belki.',
    history24h: [539, 540, 541.2, 540.8, 541.9, 542.10],
  },
  {
    id: 'pos-6',
    portfolioId: 'p2',
    ticker: 'XAU',
    name: 'Złoto (Gold Ounce)',
    category: 'gold',
    shares: 2,
    buyPrice: 2050.00,
    currentPrice: 2425.50,
    currency: 'USD',
    purchaseDate: '2023-12-01',
    commission: 12.00,
    notes: 'Zabezpieczenie przed inflacją.',
    history24h: [2410, 2415, 2420, 2418, 2422, 2425.50],
  },
  {
    id: 'pos-7',
    portfolioId: 'p3',
    ticker: 'BTC',
    name: 'Bitcoin',
    category: 'crypto',
    shares: 0.45,
    buyPrice: 42000.00,
    currentPrice: 67450.00,
    currency: 'USD',
    purchaseDate: '2024-01-08',
    commission: 15.00,
    notes: 'Zatwierdzenie spot ETF w USA.',
    history24h: [65000, 65500, 66200, 65800, 66900, 67450.00],
  },
  {
    id: 'pos-8',
    portfolioId: 'p3',
    ticker: 'SOL',
    name: 'Solana',
    category: 'crypto',
    shares: 25,
    buyPrice: 95.00,
    currentPrice: 184.20,
    currency: 'USD',
    purchaseDate: '2024-02-02',
    commission: 4.00,
    notes: 'Szybki ekosystem i meme coins boom.',
    history24h: [170, 172, 175, 178, 182, 184.20],
  }
];

export const INITIAL_ALERTS: MarketAlert[] = [
  { id: 'a1', ticker: 'BTC', name: 'Bitcoin', type: 'price_above', targetValue: 70000, currentValue: 67450, triggered: false, active: true },
  { id: 'a2', ticker: 'NVDA', name: 'NVIDIA Corp.', type: 'percent_change', targetValue: 5, currentValue: 4.85, triggered: false, active: true },
  { id: 'a3', ticker: 'AAPL', name: 'Apple Inc.', type: 'dividend', targetValue: 0.25, currentValue: 0.25, triggered: true, active: false }
];

export const NEWS_ITEMS: NewsItem[] = [
  { id: 'n1', title: 'FED sygnalizuje możliwe obniżki stóp procentowych na jesieni', source: 'Bloomberg Finance', time: '12 min temu', sentiment: 'bullish', url: '#' },
  { id: 'n2', title: 'Nvidia przejmuje kolejny startup optymalizujący LLM', source: 'Reuters Tech', time: '45 min temu', sentiment: 'bullish', url: '#' },
  { id: 'n3', title: 'Korekta na rynku miedzi i srebra po danych z azjatyckich fabryk', source: 'Financial Times', time: '2 godz. temu', sentiment: 'bearish', url: '#' },
  { id: 'n4', title: 'GPW rośnie napędzana wynikami sektora bankowego i odzieżowego', source: 'Parkiet', time: '4 godz. temu', sentiment: 'bullish', url: '#' },
  { id: 'n5', title: 'SEC zatwierdza ostateczne formularze dla funduszy Ethereum Spot ETF', source: 'CoinDesk', time: '5 godz. temu', sentiment: 'bullish', url: '#' },
];

export const DIVIDEND_CALENDAR: DividendEvent[] = [
  { id: 'd1', ticker: 'AAPL', company: 'Apple Inc.', exDate: '2026-08-10', payDate: '2026-08-17', amount: 0.25, currency: 'USD' },
  { id: 'd2', ticker: 'MSFT', company: 'Microsoft Corp.', exDate: '2026-08-15', payDate: '2026-09-10', amount: 0.75, currency: 'USD' },
  { id: 'd3', ticker: 'PKO.WA', company: 'PKO Bank Polski', exDate: '2026-08-22', payDate: '2026-09-05', amount: 2.59, currency: 'PLN' },
];

export const EARNINGS_CALENDAR: EarningEvent[] = [
  { id: 'e1', ticker: 'NVDA', company: 'NVIDIA Corporation', date: '2026-08-26', estimatedEps: 0.64 },
  { id: 'e2', ticker: 'CDR.WA', company: 'CD Projekt S.A.', date: '2026-09-02', estimatedEps: 1.45 },
  { id: 'e3', ticker: 'TSLA', company: 'Tesla Inc.', date: '2026-10-18', estimatedEps: 0.58 },
];
